---
- hosts: "{{ hosts }}"
  remote_user:  "{{ user }}"
  become: True
  tasks:
    -  name: Set sources
       copy:
          src: template/apt/sources.list
          dest: /etc/apt/sources.list
          owner: root
          group: root
          mode: 0644
    -  name: Update
       apt: 
          update_cache: yes
          upgrade: safe
    -  name: Install admin packages
       apt: 
           name: "{{ item }}"
           state: present
       with_lines: 
           - cat template/dpkg/package-lists/administration.list.binary
    -  name: Install logging packages
       apt:
           name: "{{ item }}"
           state: present
       with_lines:
           - cat template/dpkg/package-lists/logging.list.binary
    -  name: Install files packages
       apt:
           name: "{{ item }}"
           state: present
       with_lines:
           - cat template/dpkg/package-lists/files.list.binary
    -  name: Install recoup packages
       apt:
           name: "{{ item }}"
           state: present
       with_lines:
           - cat template/dpkg/package-lists/recoup.list.binary
